interval: 5m
containers:
  - name: <container name>
    image: <repo:tag>
    attachAllNetwork: true # Auto attach container to all available networks
    ignoredNetworks: [] # Networks to not attach
    volumes: []